[stable/minio] Allow providing a list of trusted certificates from Kubernetes secrets
minio/charts pull request #20
Opened 2020-09-15 20:53 UTC by tacrocha

Signed-off-by: Tacio Rocha <tacio.rocha@guavus.com>

#### Special notes for your reviewer:

This PR refers to this issue: https://github.com/minio/charts/issues/15

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[stable/minio]`)

2020-09-15 21:01 UTC, harshavardhana requested changes

2020-09-15 21:01 UTC, harshavardhana commented on minio/Chart.yaml
> +version: 6.1.2
the value has changed please update with the master @tacrocha

2020-09-15 21:16 UTC, harshavardhana requested changes
Does it not conflict with existing paths for `CAs/public.crt` elsewhere in the code base?

2020-09-16 01:58 UTC, tacrocha commented
> Does it not conflict with existing paths for `CAs/public.crt` elsewhere in the code base?

Yes, indeed. I tried and couldn't find a solution for having Minio's own public certificate together with other trusted certs, in the same mountPath, using only Kubernetes volumes and secrets. I have some options: 

1. Mount each trusted certificate on its own subdirectory of `{{ .Values.certsPath }}/CAs`. That would require Minio to recurse into subdirectories during initialization. I haven't inspected Minio's source code, but, in my tests, that did not work.
2. Use an `initContainer` to copy all the certificates mounted individually from secrets into an `emptyDir`, then mount that `emptyDir` at `{{ .Values.certsPath }}/CAs`
3. Mount the trusted certificates separately, from a secret that may contain Minio's public certificate combined with other trusted certificates. I have tested that myself by changing the `StatefulSet` directly.

Should I close this PR and bring this discussion to issue [#15](https://github.com/minio/charts/issues/15)?

2020-09-16 18:36 UTC, tacrocha commented
@harshavardhana I've updated my PR to allow the tls keys and trusted certs to coexist, by making the trusted certs a separate volume. If TLS is enabled and `trustedCerts` is empty, the chart will behave just like before and place the `public.crt` inside the `CAs` directory. If TLS is disabled and you need to trust a 3rd party certificate, you may provide a secret which contains as many certificates as needed and it'll be mounted on the `CAs` directory. If you need both TLS enabled and trusted certificates, you may simply include minios's public cert in the secret with the key being `public.crt`.

2020-09-16 19:55 UTC, harshavardhana commented
> @harshavardhana I've updated my PR to allow the tls keys and trusted certs to coexist, by making the trusted certs a separate volume. If TLS is enabled and `trustedCerts` is empty, the chart will behave just like before and place the `public.crt` inside the `CAs` directory. If TLS is disabled and you need to trust a 3rd party certificate, you may provide a secret which contains as many certificates as needed and it'll be mounted on the `CAs` directory. If you need both TLS enabled and trusted certificates, you may simply include minios's public cert in the secret with the key being `public.crt`.

@nitisht can you check this?

2020-09-21 13:25 UTC, nitisht requested changes
changes look good @tacrocha . Do you mind adding documentation about this in the README.md please?

2020-09-21 18:46 UTC, harshavardhana commented
Can update the chart to be 7.1.0? @tacrocha

2020-09-25 18:43 UTC, tacrocha commented
Hi. I've documented the new parameter in the `README` updated the chart version.

2020-09-29 23:51 UTC, harshavardhana commented
@tacrocha can you update the chart version?

2020-10-06 12:13 UTC, tacrocha commented
Chart version was updated.

2020-10-06 17:02 UTC, harshavardhana approved these changes

2020-10-08 14:05 UTC, nitisht approved these changes
LGTM, thanks @tacrocha

2020-10-08 14:09 UTC, merged